<a href="https://colab.research.google.com/github/tanupat085/ai-dep/blob/main/Data_Science_01_Number_Crunching_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q numpy scipy

# Chapter 1: Number Crunching with NumPy [https://tinyurl.com/ybgptlcf]

Prachya Boonkwan

Email: prachya.boonkwan@nectec.or.th, kaamanita@gmail.com 

(C) January 2019

Slide presentation can be found here --> **[https://tinyurl.com/yxl68949](https://tinyurl.com/yxl68949)**.

## Header

This part is the header of the code. My favorite import alias for NumPy is `np`. This is quite useful for speed coding.

In [ ]:
#!/usr/bin/env python3
#-*- coding: utf-8 -*-

import numpy as np               # for tensor computation
import numpy.random as rnd       # for randomization
import numpy.linalg as la        # for linear algebra
import scipy.sparse as sp        # for sprase matrices

*TRICK:* You can partially type in a command and press `[TAB]` to complete it. In the following line, remove the comment sign `#`, then type in `np.arr` after the equal sign. Press `[TAB]` to see a dropdown list of available commands.

In [ ]:
# my_matrix = 

-----

## 1. Vectors

### 0-Vector

- This is how we declare a vector.
- Let's begin with a 0-vector using the command `np.zeros`.
- For example, `np.zeros(3)` will create the vector $\left[ 
\begin{array}{ccc}
    0 & 0 & 0
\end{array} \right]$.

In [ ]:
vec1 = np.zeros(3)     # Change the number of elements for more fun.
print(vec1)

[0. 0. 0.]


### 1-Vector

- This is how we declare a 1-vector with the command `np.ones`.
- For example, `np.ones(3)` will create the vector $\left[ 
\begin{array}{ccc}
    1 & 1 & 1
\end{array} \right]$.

In [ ]:
vec2 = np.ones(3)      # Change the number of elements for more fun.
print(vec2)

### Custom Vector

- We declare a custom vector with `np.array`. 
- Here is how we define the vector $
\left[ \begin{array}{ccc}
    1, 2, 3
\end{array} \right]
$.

In [ ]:
vec3 = np.array([1.0, 2.0, 3.0])    # Add more elements for more fun.
print(vec3)

[1. 2. 3.]


### Size

- We can find the size of a vector with the property `shape`.

In [ ]:
print(vec3.shape)

(3,)


### Randomized Vector

- There are two ways to generate a randomized vector: `rnd.randn` for a floating point vector and `rnd.randint` for an integer vector. 

- `rnd.randn(size)` generates a floating point vector of size `size`, whose element is a floating point number drawn from a normal distribution.

In [ ]:
vec4 = rnd.randn(3)
print(vec4)

[1.2979666  1.11710101 0.18643315]


- `rnd.randint(start, end, size)` generates an integer vector of size `size`, whose element is in the range from `start` (inclusive) to `end` (exclusive).

In [ ]:
vec5 = rnd.randint(1, 10, 5)
print(vec5)

[4 9 8 8 8]


### Indexing

- We can refer to an element in a vector by indexing `[]`. Note that the index starts with 0.

In [ ]:
print(vec3[1])           # the second element

2.0


In [ ]:
print(vec3[2])           # the third element

3.0


In [ ]:
# print(vec3[20])          # This will cause an error message due to out-of-bounds indexing

IndexError: ignored

### Element Setting

- We can also set the value of a vector's element by indexing `[]`.
- For example, let's set the second element of `vec3` to be 100.

In [ ]:
vec5 = np.array([1.0, 2.0, 3.0])

print(f'Before: vec5 = {vec5}')
vec5[1] = 100            # Set the second element to be 100.
print(f'After : vec5 = {vec5}')

Before: vec5 = [1. 2. 3.]
After : vec5 = [  1. 100.   3.]


### Dot Product

- We can compute the dot product of two vectors by the operator `@`. 
- For example, let's compute the dot product of `vec6` and `vec7`.

In [ ]:
vec6 = np.array([5, 6, 7, 8])
vec7 = np.array([9, 10, 11, 12])
dotval = vec6 @ vec7
print(dotval)

278


- We can also use the method `dot` of the first operand.

In [ ]:
dotval = vec6.dot(vec7)
print(dotval)

278


### Vector Norm

- We can also compute the norm (i.e. size) of a vector $\left\| \mathbf{v} \right\|$ by the command `la.norm`.
- The command computes Frobenius norm, where:
$$
\begin{eqnarray}
    \left\| \mathbf{v} \right\| & = & \mathrm{Frobenius}(\mathbf{v}) \\
    & = & \sqrt{ \sum_{i = 1}^N v_i^2 } \\
    & = & \sqrt{ v_1^2 + v_2^2 + v_3^2 + \ldots + v_N^2 }
\end{eqnarray}
$$

In [ ]:
vecnorm = la.norm(vec6)
print(vecnorm)

13.19090595827292


-----

## Exercises 1

### Question 1.1

Compute $\mathbf{a} + 4 \mathbf{b} - 3 \mathbf{c}$, where
$$
\begin{eqnarray}
    \mathbf{a} & = & \left[  \begin{array}{ccc}
        1 & 1 & 1
    \end{array} \right] \\
    \mathbf{b} & = & \left[  \begin{array}{ccc}
        4 & 5 & 6
    \end{array} \right] \\
    \mathbf{c} & = & \left[  \begin{array}{ccc}
        0 & 0 & 0
    \end{array} \right]
\end{eqnarray}
$$

In [ ]:
# vec_a = __________           # Fill in these blanks
# vec_b = __________
# vec_c = __________
# result = __________
# 
# print(f'result = {result}')

#### Solution

In [ ]:
vec_a = np.ones(3)
vec_b = np.array([4, 5, 6])
vec_c = np.zeros(3)
result = vec_a + 4 * vec_b - 3 * vec_c

print(f'result = {result}')

result = [17. 21. 25.]


### Question 1.2

Compute $10 \times \mathbf{a} \cdot \mathbf{b}$, where $\mathbf{a}$ and $\mathbf{b}$ are randomized vectors of size 10.

In [ ]:
# vec_a = __________           # Fill in these blanks
# vec_b = __________
# result = __________
# 
# print(f'result = {result}')

#### Solution

In [ ]:
vec_a = rnd.randn(10)
vec_b = rnd.randn(10)
result = 10 * vec_a @ vec_b

print(f'result = {result}')

result = -14.824611541203035


### Question 1.3

Create a vector of size 32 named `vec_nums`. Each even-indexed cell contains an even number from 0 to 30, ascendingly sorted. And each odd-indexed cell contains an odd number from 31 to 1, descendingly sorted. The result should look like this:

```python
[0, 31, 2, 29, 4, 27, ..., 26, 5, 28, 3, 30, 1]
```

In [ ]:
# vec_nums = np.zeros(32, dtype=np.int64)      # The datatype is 64-bit integer
# 
# # Loop over the index i and fill up the vector according to the index.
# for i in range(32):
#     __________
# 
# print(vec_nums)

##### Solution

In [ ]:
vec_nums = np.zeros(32, dtype=np.int64)      # The datatype is 64-bit integer

# Loop over the index i and fill up the vector according to the index.
for i in range(32):
    if i % 2 == 0:
        vec_nums[i] = i
    else:
        vec_nums[i] = 32 - i

print(vec_nums)

[ 0 31  2 29  4 27  6 25  8 23 10 21 12 19 14 17 16 15 18 13 20 11 22  9
 24  7 26  5 28  3 30  1]


### Question 1.4

Compute a unit vector of `vec_nums`.

$$
\begin{eqnarray}
    \mathrm{unit}(\mathbf{v}) & = & \frac{\mathbf{v}}{\left\| \mathbf{v} \right\|}
\end{eqnarray}
$$

In [ ]:
# unit_vecnums = __________          # Fill in this blank
# 
# print(unit_vecnums)

#### Solution

In [ ]:
unit_vecnums = vec_nums / la.norm(vec_nums)

print(unit_vecnums)

[0.         0.30374645 0.01959655 0.2841499  0.03919309 0.26455336
 0.05878964 0.24495681 0.07838618 0.22536027 0.09798273 0.20576372
 0.11757927 0.18616718 0.13717582 0.16657063 0.15677236 0.14697409
 0.17636891 0.12737754 0.19596545 0.107781   0.215562   0.08818445
 0.23515854 0.06858791 0.25475509 0.04899136 0.27435163 0.02939482
 0.29394818 0.00979827]


-----
## 2. Matrices

### 0-Matrix

- This is how we declare a matrix.
- A 0-matrix can again be defined with `np.zeros`, but this time we identify the size of each dimension (a.k.a. the *shape*), too.
- For example, `np.zeros((3, 4))` will create the matrix

$$\left[ 
\begin{array}{cccc}
    0 & 0 & 0 & 0 \\
    0 & 0 & 0 & 0 \\
    0 & 0 & 0 & 0
\end{array} \right]_{3 \times 4}
$$

In [ ]:
mat1 = np.zeros((3, 4))     # Change the number of elements on any dimension.
print(mat1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- The reason of putting an extra pair of parentheses over the shape is because the next parameter of all array creation functions is the data type `dtype`.
- This data type can be floating point `np.float`{16, 32, 64, 128}, integer `np.int`{8, 16, 32, 64}, and complex numbers `np.complex`.
- The default data type is `np.float64`.

In [ ]:
mat1 = np.zeros((3, 4), dtype=np.float64)      # each element is of the type 64-bit floating point
print(mat1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 1-Matrix

- We define a 1-matrix with `np.ones` in the same fashion. 
- For example, `np.ones((3, 4))` will create the matrix
$$\left[ 
\begin{array}{cccc}
    1 & 1 & 1 & 1 \\
    1 & 1 & 1 & 1 \\
    1 & 1 & 1 & 1
\end{array} \right]_{3 \times 4}
$$

In [ ]:
mat2 = np.ones((3, 4))      # Change the number of elements on any dimension.
print(mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Identity Matrix

- This is how you define an identity matrix with `np.eye`. 
- For example, `np.eye(3)` will create the 3-dimensional identity matrix
$$\left[ 
\begin{array}{ccc}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
\end{array} \right]_{3 \times 3}
$$

In [ ]:
mat3 = np.eye(3)       # Change the number of elements on any dimension.
print(mat3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- We can also determine the number of columns if we desire a non-square matrix.

In [ ]:
mat3 = np.eye(3, 4)       # Change the number of elements on any dimension.
print(mat3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### Randomized Matrix

- We define a randomized matrix with `rnd.randn` (floating point) and `rnd.randint` (integer).

In [ ]:
mat_rand = rnd.randn(3, 4)        # Change the number of elements on any dimension.
print(mat_rand)

[[-1.1490691  -0.97518228 -0.38405128  0.61034464]
 [-0.32819544  0.28607575 -0.89170096 -0.24156482]
 [-0.52478983  0.37278638  1.82893328 -1.13589812]]


In [ ]:
mat_randint = rnd.randint(1, 10, (3, 4))
print(mat_randint)

[[4 7 6 6]
 [8 6 1 9]
 [6 9 4 6]]


### Custom Matrix

- A custom matrix can be defined with `np.array`. 
- Notice that a 2-dimensional matrix is just a list of lists.
- Here we define the matrix
$$
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]_{2 \times 3}
$$
- Each row becomes a list. For example, the first row becomes `[1, 2, 3]`, and the second row, `[4, 5, 6]`.

In [ ]:
# Play with the elements, rows, or columns for more fun.
mat4 = np.array( [ [1, 2, 3],
                   [4, 5, 6] ] )
print(mat4)

[[1 2 3]
 [4 5 6]]


### Shape

- We can also find the size of a matrix with the property `shape`.

In [ ]:
print(mat4.shape)

(2, 3)


### Cell Indexing and Setting

- We can refer to a particular cell of a matrix by indexing `[]`.

In [ ]:
print(mat4[0,1])            # cell (1,2)

2


In [ ]:
print(mat4[1,2])            # cell (2,3)

6


In [ ]:
mat4 = np.array( [ [1, 2, 3],
                   [4, 5, 6] ] )

print(f'Before: mat4 =\n{mat4}')
mat4[1,2] = 100             # Set the value of cell (2,3) to be 100.
print(f'After : mat4 =\n{mat4}')

Before: mat4 =
[[1 2 3]
 [4 5 6]]
After : mat4 =
[[  1   2   3]
 [  4   5 100]]


### Row Indexing

- We can index a row of a matrix by `[]`, too.

In [ ]:
mat5 = np.array( [ [1, 2, 3],
                   [4, 5, 6] ] )

print(f'row 1 of mat5 = {mat5[0]}')
print(f'row 2 of mat5 = {mat5[1]}')

row 1 of mat5 = [1 2 3]
row 2 of mat5 = [4 5 6]


### Row Setting

- Setting a row is as simple. For example, we can replace the first row of `mat5` by setting `mat5[0]` to be another vector.

In [ ]:
mat5 = np.array( [ [1, 2, 3],
                   [4, 5, 6] ] )

print(f'Before: mat5 =\n{mat5}')
mat5[0] = np.array([7, 8, 9])
print(f'After : mat5 =\n{mat5}')

Before: mat5 =
[[1 2 3]
 [4 5 6]]
After : mat5 =
[[7 8 9]
 [4 5 6]]


### Column Indexing

- We can also get access to a column of a matrix by replacing the row index with `:`.

In [ ]:
mat6 = np.array( [ [1, 2, 3],
                   [4, 5, 6] ] )

print(f'column 1 of mat6 = {mat6[:, 0]}')
print(f'column 2 of mat6 = {mat6[:, 1]}')
print(f'column 3 of mat6 = {mat6[:, 2]}')

column 1 of mat6 = [1 4]
column 2 of mat6 = [2 5]
column 3 of mat6 = [3 6]


### Column Setting

- Setting a column can be as simple. For example, we can replace the first column of `mat6` by setting `mat6[:, 0]` to be another vector.

In [ ]:
mat6 = np.array( [ [1, 2, 3],
                   [4, 5, 6] ] )

print(f'Before: mat6 =\n{mat6}')
mat6[:, 0] = np.array([7, 8])
print(f'After : mat6 =\n{mat6}')

Before: mat6 =
[[1 2 3]
 [4 5 6]]
After : mat6 =
[[7 2 3]
 [8 5 6]]


### Matrix stacking

- We can stack two matrices with the following commands:

  - `np.hstack` for horizontal stacking
  - `np.vstack` for vertical stacking
  -  `np.concatenate` for concatenation on a specified axis

- The last command is a generalization of the previous two. Note that these commands require a tuple of matrices to be stacked.

**Vertical stacking `np.vstack`**

$$
\begin{eqnarray}
    \left[ \begin{array}{ccc}
        1 & 2 & 3 \\
        4 & 5 & 6
    \end{array} \right]_{2 \times 3}
    \oplus_0
    \left[ \begin{array}{ccc}
        7 & 8 & 9 \\
        10 & 11 & 12
    \end{array} \right]_{2 \times 3}
    & = &
    \left[ \begin{array}{ccc}
        1 & 2 & 3 \\
        4 & 5 & 6 \\
        7 & 8 & 9 \\
        10 & 11 & 12
    \end{array} \right]_{4 \times 3}
\end{eqnarray}
$$

**Horizontal stacking `np.hstack`**

$$
\begin{eqnarray}
    \left[ \begin{array}{ccc}
        1 & 2 & 3 \\
        4 & 5 & 6
    \end{array} \right]_{2 \times 3}
    \oplus_1
    \left[ \begin{array}{ccc}
        7 & 8 & 9 \\
        10 & 11 & 12
    \end{array} \right]_{2 \times 3}
    & = &
    \left[ \begin{array}{ccc}
        1 & 2 & 3 & 7 & 8 & 9 \\
        4 & 5 & 6 & 10 & 11 & 12
    \end{array} \right]_{2 \times 6}
\end{eqnarray}
$$

- The operator $\oplus_k$ is concatenation of matrices on axis $k$. `np.vstack` is equivalent to $\oplus_0$, and `np.hstack`, $\oplus_1$.

In [ ]:
mat_a = np.array([ [1, 2, 3],
                   [4, 5, 6] ])

mat_b = np.array([ [ 7,  8,  9],
                   [10, 11, 12] ])

mat_c = np.array([ [13, 14, 15],
                   [16, 17, 18],
                   [19, 20, 21],
                   [22, 23, 24] ])

print(f'hstack(A, B) =\n{ np.hstack((mat_a, mat_b)) }\n')
print(f'vstack(A, C) =\n{ np.vstack((mat_a, mat_c)) }\n')

print(f'hstack = concatenate(A, B) on axis 1 (row)\n{ np.concatenate((mat_a, mat_b), axis=1) }\n')
print(f'vstack = concatenate(A, C) on axis 0 (column)\n{ np.concatenate((mat_a, mat_c), axis=0) }\n')

hstack(A, B) =
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

vstack(A, C) =
[[ 1  2  3]
 [ 4  5  6]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

hstack = concatenate(A, B) on axis 1 (row)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

vstack = concatenate(A, C) on axis 0 (column)
[[ 1  2  3]
 [ 4  5  6]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]



### Matrix Norm

- We can compute the size of a matrix $\left\| \mathbf{A} \right\|$ by the command `la.norm`.
- The command computes Frobenius norm, where:
$$
\begin{eqnarray}
    \left\| \mathbf{A} \right\| & = & \mathrm{Frobenius}(\mathbf{A}) \\
    & = & \sqrt{ \sum_{i = 1}^M \sum_{j = 1}^N a_{ij}^2 } \\
    & = & \sqrt{ a_{11}^2 + a_{12}^2 + a_{13}^2 + \ldots + a_{MN}^2 }
\end{eqnarray}
$$

In [ ]:
mat6 = np.array( [ [1, 2, 3],
                   [4, 5, 6] ] )

matnorm = la.norm(mat6)
print(matnorm)

9.539392014169456


- We can also compute the norm by projection on a particular axis by specifying the argument `axis`.

In [ ]:
vec_norms_0 = la.norm(mat6, axis=0)
vec_norms_1 = la.norm(mat6, axis=1)
print(vec_norms_0)
print(vec_norms_1)

[4.12310563 5.38516481 6.70820393]
[3.74165739 8.77496439]


-----
## Exercises 2

### Question 2.1

Construct the following matrices.

$$
\begin{eqnarray}
    \mathbf{A} & = &
    \left[ \begin{array}{cc}
        1 & 2 \\
        3 & 4
    \end{array} \right] \\
    \mathbf{B} & = &
    \left[ \begin{array}{cc}
        5 & 6 \\
        7 & 8
    \end{array} \right] \\
    \mathbf{C} & = &
    \left[ \begin{array}{cccc}
        9 & 10 & 11 & 12 \\
        13 & 14 & 15 & 16
    \end{array} \right] 
\end{eqnarray}
$$

In [ ]:
# mat_a = __________
# mat_b = __________
# mat_c = __________
# 
# print(f'A =\n{mat_a}\n')
# print(f'B =\n{mat_b}\n')
# print(f'C =\n{mat_c}\n')

#### Solution

In [ ]:
mat_a = np.array([ [1, 2],
                   [3, 4] ])
mat_b = np.array([ [5, 6],
                   [7, 8] ])
mat_c = np.array([ [ 9, 10, 11, 12],
                   [13, 14, 15, 16] ])

print(f'A =\n{mat_a}\n')
print(f'B =\n{mat_b}\n')
print(f'C =\n{mat_c}\n')

A =
[[1 2]
 [3 4]]

B =
[[5 6]
 [7 8]]

C =
[[ 9 10 11 12]
 [13 14 15 16]]



### Question 2.2

Concatenate the matrices created in Question 2.1 to construct the following matrices. Feel free to use `np.hstack`, `np.vstack`, and `np.concatenate`.

$$
\begin{eqnarray}
    \mathbf{D} & = &
    \left[ \begin{array}{cccc}
        1 & 2 & 5 & 6 \\
        3 & 4 & 7 & 8
    \end{array} \right] \\
    \mathbf{E} & = &
    \left[ \begin{array}{cc}
        1 & 2 \\
        3 & 4 \\
        5 & 6 \\
        7 & 8
    \end{array} \right] \\
    \mathbf{F} & = &
    \left[ \begin{array}{cccc}
        1 & 2 & 5 & 6 \\
        3 & 4 & 7 & 8 \\
        9 & 10 & 11 & 12 \\
        13 & 14 & 15 & 16
    \end{array} \right] 
\end{eqnarray}
$$

In [ ]:
# mat_d = __________
# mat_e = __________
# mat_f = __________
# 
# print(f'D =\n{mat_d}\n')
# print(f'E =\n{mat_e}\n')
# print(f'F =\n{mat_f}\n')

#### Solution

In [ ]:
mat_d = np.hstack([mat_a, mat_b])
mat_e = np.vstack([mat_a, mat_b])
mat_f = np.vstack([mat_d, mat_c])

print(f'D =\n{mat_d}\n')
print(f'E =\n{mat_e}\n')
print(f'F =\n{mat_f}\n')

D =
[[1 2 5 6]
 [3 4 7 8]]

E =
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

F =
[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]



-----
## 3. Matrix Computation

- In NumPy, vectors and matrices are treated similarly.
- Therefore, we can apply mathematical operations such as addition and multiplication on vectors and matrices, given that they have identical shapes.
- Let me define two matrices for our short demonstration.

In [ ]:
m1 = np.array( [ [1, 2, 3],
                 [4, 5, 6] ] )
m2 = np.array( [ [ 7,  8,  9],
                 [10, 11, 12] ] )
print(f'm1 =\n{m1}')
print(f'm2 =\n{m2}')

m1 =
[[1 2 3]
 [4 5 6]]
m2 =
[[ 7  8  9]
 [10 11 12]]


### Addition and Subtraction

- We use `+` and `-`, respectively.

$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right] + \left[ \begin{array}{ccc}
    7 & 8 & 9 \\
    10 & 11 & 12
\end{array} \right] & = & \left[ \begin{array}{ccc}
    8 & 10 & 12 \\
    14 & 16 & 18
\end{array} \right]
\end{eqnarray}
$$

In [ ]:
m_add = m1 + m2
print(f'm1 + m2 =\n{m_add}')

m1 + m2 =
[[ 8 10 12]
 [14 16 18]]


$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    7 & 8 & 9 \\
    10 & 11 & 12
\end{array} \right] - \left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right] & = & \left[ \begin{array}{ccc}
    6 & 6 & 6 \\
    6 & 6 & 6
\end{array} \right]
\end{eqnarray}
$$

In [ ]:
m_sub = m2 - m1
print(f'm2 - m1 =\n{m_sub}')

m2 - m1 =
[[6 6 6]
 [6 6 6]]


### Transpose

- We use the property `T` to transpose a matrix.

$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]^\top & = & \left[ \begin{array}{cc}
    1 & 4 \\
    2 & 5 \\
    3 & 6
\end{array} \right]
\end{eqnarray}
$$

In [ ]:
m_trans = m1.T
print(f'transpose(m1) =\n{m_trans}')

transpose(m1) =
[[1 4]
 [2 5]
 [3 6]]


### Scalar Multiplication

- We simply use the operator `*`.

$$
\begin{eqnarray}
4 \times \left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right] & = & \left[ \begin{array}{ccc}
    4 & 8 & 12 \\
    16 & 20 & 24
\end{array} \right]
\end{eqnarray}
$$

In [ ]:
m_smult = 4 * m1
print(f'4 × m1 =\n{m_smult}')

4 × m1 =
[[ 4  8 12]
 [16 20 24]]


### Matrix Multiplication

- We use the operator `@`.
- Do *NOT* use the operator `*` as it is for element-wise multiplication.

$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]_{2 \times 3} \times \left[ \begin{array}{cc}
    7 & 10 \\
    8 & 11 \\
    9 & 12
\end{array} \right]_{3 \times 2} & = & \left[ \begin{array}{cc}
    50 & 68 \\
    122 & 167
\end{array} \right]_{2 \times 2}
\end{eqnarray}
$$

In [ ]:
m_mult = m1 @ m2.T
print(f'm1 × transpose(m2) =\n{m_mult}')

m1 × transpose(m2) =
[[ 50  68]
 [122 167]]


- Note that multiplication of `m1` and `m2` would not work due to dimension mismatch.
$$
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]_{2 \times 3} \times \left[ \begin{array}{ccc}
    7 & 8 & 9 \\
    10 & 11 & 12
\end{array} \right]_{2 \times 3}
$$

In [ ]:
# print(m1 @ m2)       # This will cause an error message.

ValueError: ignored

### Element-wise Multiplication

- We use the operator `*` for element-wise multiplication.
$$
\begin{eqnarray}
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6
\end{array} \right]_{2 \times 3} \otimes \left[ \begin{array}{ccc}
    7 & 8 & 9 \\
    10 & 11 & 12
\end{array} \right]_{2 \times 3} & = & \left[ \begin{array}{ccc}
    7 & 16 & 27 \\
    40 & 55 & 72
\end{array} \right]_{2 \times 3}
\end{eqnarray}
$$

In [ ]:
m_emult = m1 * m2
print(f'm1 * m2 =\n{m_emult}')

m1 * m2 =
[[ 7 16 27]
 [40 55 72]]


### Vector-wise Operations via Broadcasting

- For a binary operator e.g. `+`, `-`, `*` and `/`, if one operand is a matrix and the other one is a vector, the vector will be mapped to each row of the matrix before applying that operator element-wise. This procedure is called *broadcasting*.
- For example,
$$
\begin{eqnarray}
    \left[ \begin{array}{ccc}
        1 & 3 & 2 \\
        2 & 2 & 1 \\
        3 & 1 & 3
    \end{array} \right]
    *
    \left[ \begin{array}{ccc}
        4 & 5 & 10
    \end{array} \right]
    & = &
    \left[ \begin{array}{ccc}
        4 & 15 & 20 \\
        8 & 10 & 10 \\
        12 & 5 & 30
    \end{array} \right]
\end{eqnarray}
$$

In [ ]:
vec_a = np.array([ [1,3,2],
                   [2,2,1],
                   [3,1,3] ])
vec_b = np.array([4, 5, 10])

print(vec_a * vec_b)

[[ 4 15 20]
 [ 8 10 10]
 [12  5 30]]


- For example,
$$
\begin{eqnarray}
    \left[ \begin{array}{ccc}
        1 & 3 & 2 \\
        2 & 2 & 1 \\
        3 & 1 & 3
    \end{array} \right]
    /
    \left[ \begin{array}{ccc}
        4 & 5 & 10
    \end{array} \right]
    & = &
    \left[ \begin{array}{ccc}
        0.25 & 0.6 & 0.2 \\
        0.5 & 0.4 & 0.1 \\
        0.75 & 0.2 & 0.3
    \end{array} \right]
\end{eqnarray}
$$

In [ ]:
vec_a = np.array([ [1,3,2],
                   [2,2,1],
                   [3,1,3] ])
vec_b = np.array([4, 5, 10])

print(vec_a / vec_b)

[[0.25 0.6  0.2 ]
 [0.5  0.4  0.1 ]
 [0.75 0.2  0.3 ]]


-----
## Exercises 3

### Question 3.1

Define the following matrices and compute $\mathbf{A} + \mathbf{B} + 4 \mathbf{C}$, where

$$
\begin{eqnarray}
    \mathbf{A} & = & \left[ \begin{array}{ccc}
        0 & 0 & 0 \\
        0 & 0 & 0
    \end{array} \right] \\
    \mathbf{B} & = & \left[ \begin{array}{ccc}
        1 & 1 & 1 \\
        1 & 1 & 1
    \end{array} \right] \\
    \mathbf{C} & = & \left[ \begin{array}{ccc}
        1 & 0 & 0 \\
        0 & 1 & 0
    \end{array} \right] \\
\end{eqnarray}
$$

In [ ]:
# mat_a = np.zeros( _____ )        # Fill in these blanks
# mat_b = np.ones( _____ )
# mat_c = np.eye( _____ )
# result = __________
# print(result)

#### Solution

In [ ]:
mat_a = np.zeros((2, 3))
mat_b = np.ones((2, 3))
mat_c = np.eye(2, 3)
result = mat_a + mat_b + 4 * mat_c
print(result)

[[5. 1. 1.]
 [1. 5. 1.]]


### Question 3.2

Compute $\mathbf{A}^\top \times \mathbf{A}$, where $\mathbf{A}$ is a randomized matrix of shape $(3, 4)$.

In [ ]:
# mat_a = np.random.randn( _____ )        # Fill in these blanks
# result = __________
# print(result)

#### Solution

In [ ]:
mat_a = np.random.randn(3, 4)        # Fill in these blanks
result = mat_a.T @ mat_a
print(result)

[[1.41950012 1.67762685 2.13614108 0.58961153]
 [1.67762685 2.07146447 2.44442475 0.67097498]
 [2.13614108 2.44442475 3.99002388 0.51970322]
 [0.58961153 0.67097498 0.51970322 0.46979735]]


### Question 3.3

Compute $ \left( \mathbf{A} \otimes \mathbf{B} \right)^\top \times \mathbf{C}^\top $, where $\mathbf{A}$, $\mathbf{B}$, and $\mathbf{C}$ are randomized matrices of shapes (2, 3), (2, 3), and (3, 2), respectively.

In [ ]:
# mat_a = np.random.randn( _____ )        # Fill in these blanks
# mat_b = np.random.randn( _____ )
# mat_c = np.random.randn( _____ )
# result = __________
# print(result)

#### Solution

In [ ]:
mat_a = np.random.randn(2, 3)
mat_b = np.random.randn(2, 3)
mat_c = np.random.randn(3, 2)
result = (mat_a * mat_b).T @ mat_c.T
print(result)

[[-0.09764487  0.13164273 -0.13167047]
 [-0.11629672  0.15515451 -0.14929548]
 [-0.13281072  0.18051556 -0.18582795]]


### Question 3.4

Compute $ \mathbf{R} = \mathbf{A}^\top \times \mathbf{A} $, where $\mathbf{A}$ is a randomized matrix of shape (3, 4). Then replace the first column with a random vector.

In [ ]:
# mat_a = rnd.randn( _____ )
# mat_r = __________
# print(mat_r)
# 
# mat_r[ _____ ] = __________
# print(mat_r)

#### Solution

In [ ]:
mat_a = rnd.randn(3, 4)
mat_r = mat_a.T @ mat_a
print(mat_r)

mat_r[:, 0] = rnd.randn(4)
print(mat_r)

[[ 0.31782455  0.36109849 -1.31898215 -0.47195717]
 [ 0.36109849  1.11081698 -1.82903102 -0.34154552]
 [-1.31898215 -1.82903102  5.99239812  2.44795641]
 [-0.47195717 -0.34154552  2.44795641  1.68610753]]
[[-1.25894992  0.36109849 -1.31898215 -0.47195717]
 [ 0.16816898  1.11081698 -1.82903102 -0.34154552]
 [ 1.62136937 -1.82903102  5.99239812  2.44795641]
 [-1.05984397 -0.34154552  2.44795641  1.68610753]]


### Question 3.5

Construct matrix $\mathbf{F}$, where
$$
\begin{eqnarray}
\mathbf{F} & = &
    \left[ \begin{array}{cccc}
        1 & 2 & 3 & 4 \\
        5 & 6 & 7 & 8 \\
        9 & 10 & 11 & 12 \\
        13 & 14 & 15 & 16
    \end{array} \right] 
\end{eqnarray}
$$
Then convert each *column* of $\mathbf{F}$ into a unit vector using vector-wise operation.

In [ ]:
# mat_f = __________
# vec_norms = __________
# 
# result = __________
# 
# print(result)

#### Solution

In [ ]:
mat_f = np.array([ [ 1,  2,  3,  4],
                   [ 5,  6,  7,  8],
                   [ 9, 10, 11, 12],
                   [13, 14, 15, 16] ])
vec_norms = la.norm(mat_f, axis=0)

result = mat_f / vec_norms

print(result)

[[0.06019293 0.10910895 0.14925558 0.18257419]
 [0.30096463 0.32732684 0.34826302 0.36514837]
 [0.54173634 0.54554473 0.54727045 0.54772256]
 [0.78250805 0.76376262 0.74627789 0.73029674]]


### Question 3.6

Check if each column vector of $\mathbf{F}$ is a unit vector. The norm of a unit vector should be equal or very close to 1. In this question, we say that two real numbers $r_1$ and $r_2$ are very close to each other if $\left| r_1 - r_2 \right| < \epsilon$, where $\epsilon$ is a very small real number e.g. $10^{-6}$.

In [ ]:
# for col in range( __________ ):
#     if not __________ :
#         print(f'Column {col} is not a unit vector!')

#### Solution

In [ ]:
for col in range(result.shape[0]):
    if not (abs(la.norm(result[:, col]) - 1.0) <= 1e-6):
        print(f'Column {col} is not a unit vector!')

-----
## 4. Tensors

### Tensor as Data Batches

- Tensor is essentially an $N$-dimensional array. It is a generalized form of data collection, where its dimension can be greater than 2.
- In mathematics, we call $N$ the rank of the tensor, and we say that this is a *rank-$N$ tensor*.
- Therefore, any scalar quantity is a rank-0 tensor, any vector is a rank-1 tensor, while any matrix is a rank-2 tensor.
- For the sake of analogy, we can consider any tensor of rank greater than two as a collection of matrices, a.k.a. *batches*.

- For example, we can create a rank-3 tensor $\mathbf{A} = \left[ \begin{array}{c}
    \mathbf{A}_1 \\
    \mathbf{A}_2 
\end{array} \right]$, where $A_1$ and $A_2$ are two batches of data:
$$
\begin{eqnarray}
    \mathbf{A}_1 & = &
    \left[ \begin{array}{cc}
        1 & 2 \\
        3 & 4
    \end{array} \right] \\
    \mathbf{A}_2 & = &
    \left[ \begin{array}{cc}
        5 & 6 \\
        7 & 8
    \end{array} \right]
\end{eqnarray}
$$

- Note that `numpy` separates $\mathbf{A}_1$ and $\mathbf{A}_2$ with a blank line when printed out.

In [ ]:
# tsr_a is a 3-dimensional tensor consisting of two matrices
tsr_a = np.array([ [ [1, 2],           # matrix 1
                     [3, 4] ],
                   [ [5, 6],           # matrix 2
                     [7, 8] ] ])
print(tsr_a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- The above tensor can also be rewritten as follows:
$$
\begin{eqnarray}
    \mathbf{A} & = &
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array} \right]
        \\
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8
        \end{array} \right]
    \end{array} \right]
\end{eqnarray}
$$
whose shape is `(2, 2, 2)`.

In [ ]:
print(tsr_a.shape)

(2, 2, 2)


- In the case where rank $N > 3$, more than one blank line is used to separate between dimensions.
- For example, in rank-4 tensor $\mathbf{B}$, the two blank lines separate the first dimension, while each blank line separate the second dimension.

$$
\begin{eqnarray}
    \mathbf{B} & = &
    \left[ \begin{array}{cc}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array} \right]
        &
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            9 & 10 \\
            11 & 12
        \end{array} \right]
        &
        \left[ \begin{array}{cc}
            13 & 14 \\
            15 & 16
        \end{array} \right]
    \end{array} \right]
\end{eqnarray}
$$

In [ ]:
tsr_b = np.array([ [ [ [1, 2],
                       [3, 4] ],
                     [ [5, 6],
                       [7, 8] ] ],
                   [ [ [9, 10],
                       [11, 12] ],
                     [ [13, 14],
                       [15, 16] ] ] ])
print(tsr_b)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


### Indexing and Setting

- We can do indexing and setting on a tensor simply by `[]` and `:` as if we are dealing with vectors and matrices. 
- For example, let's consider tensor $\mathbf{B}$.

$$
\begin{eqnarray}
    \mathbf{B} & = &
    \left[ \begin{array}{cc}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array} \right]
        &
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            9 & 10 \\
            11 & 12
        \end{array} \right]
        &
        \left[ \begin{array}{cc}
            13 & 14 \\
            15 & 16
        \end{array} \right]
    \end{array} \right]
\end{eqnarray}
$$

In [ ]:
tsr_b = np.array([ [ [ [1, 2],
                       [3, 4] ],
                     [ [5, 6],
                       [7, 8] ] ],
                   [ [ [9, 10],
                       [11, 12] ],
                     [ [13, 14],
                       [15, 16] ] ] ])
print(f'Tensor B:\n{tsr_b}')
print(f'Shape of B = {tsr_b.shape}')

Tensor B:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Shape of B = (2, 2, 2, 2)


- How can we get access to the cell in which 7 is in? The number 7 is in the matrix in row 1, column 2; therefore, we want to address $\mathbf{B}_{1, 2}$. Then, we further address the cell of 7, which is in row 2, column 1.
- Therefore, we obtain that:
$$
\begin{eqnarray}
    B_{1, 2, 2, 1} & = & 7
\end{eqnarray}
$$

In [ ]:
print(f'B[0,1,1,0] = { tsr_b[0, 1, 1, 0] }')        # row 1, column 2, row 2, column 1

B[0,1,1,0] = 7


- By placing `:` in a specific dimension, we can now get access to a specified row or column.

In [ ]:
print(f'B[0,1,1,:] = { tsr_b[0, 1, 1, :] }')        # row 1, column 2, row 2, all columns
print(f'B[0,1,:,0] = { tsr_b[0, 1, :, 0] }')        # row 1, column 2, all rows, column 1
print(f'B[0,:,1,0] = { tsr_b[0, :, 1, 0] }')        # row 1, all columns, row 2, column 1
print(f'B[:,1,1,0] = { tsr_b[:, 1, 1, 0] }')        # all rows, column 2, row 2, column 1

B[0,1,1,:] = [7 8]
B[0,1,:,0] = [5 7]
B[0,:,1,0] = [3 7]
B[:,1,1,0] = [ 7 15]


- Of course, we can place `:` on more than one dimension, resulting in access to a matrix or even a tensor.

In [ ]:
print(f'B[0,1,:,:] =\n{ tsr_b[0, 1, :, :] }\n')        # row 1, column 2, all rows, all columns
print(f'B[0,:,:,0] =\n{ tsr_b[0, :, :, 0] }\n')        # row 1, all columns, all rows, column 1
print(f'B[:,:,1,0] =\n{ tsr_b[:, :, 1, 0] }')          # all rows, all columns, row 2, column 1

B[0,1,:,:] =
[[5 6]
 [7 8]]

B[0,:,:,0] =
[[1 3]
 [5 7]]

B[:,:,1,0] =
[[ 3  7]
 [11 15]]


In [ ]:
print(f'B[0,:,:,:] =\n{ tsr_b[0, :, :, :] }\n')        # row 1, all columns, all rows, all columns
print(f'B[:,1,:,:] =\n{ tsr_b[:, 1, :, :] }\n')        # all rows, column 2, all rows, all columns
print(f'B[:,:,1,:] =\n{ tsr_b[:, :, 1, :] }\n')        # all rows, all columns, row 2, all columns
print(f'B[:,:,:,0] =\n{ tsr_b[:, :, :, 0] }')          # all rows, all columns, all rows, column 1

B[0,:,:,:] =
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

B[:,1,:,:] =
[[[ 5  6]
  [ 7  8]]

 [[13 14]
  [15 16]]]

B[:,:,1,:] =
[[[ 3  4]
  [ 7  8]]

 [[11 12]
  [15 16]]]

B[:,:,:,0] =
[[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]


- **Tips for advanced programmers:** If we fix one or both ends of the index sequence, we can replace consecutive `:`'s with `...`

In [ ]:
print(f'B[0,...] =\n{   tsr_b[0, ...]    }\n')      # equals to tsr_b[0, :, :, :]
print(f'B[:,1,...] =\n{ tsr_b[:, 1, ...] }\n')      # equals to tsr_b[:, 1, :, :]
print(f'B[...,1,:] =\n{ tsr_b[..., 1, :] }\n')      # equals to tsr_b[:, :, 1, :]
print(f'B[...,0] =\n{   tsr_b[..., 0]    }\n')      # equals to tsr_b[:, :, :, 0]
print(f'B[0,...,0] =\n{ tsr_b[0, ..., 0] }')        # equals to tsr_b[0, :, :, 0]

B[0,...] =
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

B[:,1,...] =
[[[ 5  6]
  [ 7  8]]

 [[13 14]
  [15 16]]]

B[...,1,:] =
[[[ 3  4]
  [ 7  8]]

 [[11 12]
  [15 16]]]

B[...,0] =
[[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]

B[0,...,0] =
[[1 3]
 [5 7]]


- We can also get access to an inner array by simple indexing.
- For example, we can access $\mathbf{B}_{1,2}$ by `tsr_b[0, 1]`.

In [ ]:
print(tsr_b[0, 1])

[[5 6]
 [7 8]]


### Tensor Stacking

- We can still use the command `np.concatenate` to stack up tensors on a specified axis.

$$
\begin{eqnarray}
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8
        \end{array} \right]
    \end{array} \right]
    \oplus_0
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            9 & 10 \\
            11 & 12
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            13 & 14 \\
            15 & 16
        \end{array} \right]
    \end{array} \right]
    & = &
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            9 & 10 \\
            11 & 12
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            13 & 14 \\
            15 & 16
        \end{array} \right]
    \end{array} \right] \\
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8
        \end{array} \right]
    \end{array} \right]
    \oplus_1
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            9 & 10 \\
            11 & 12
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            13 & 14 \\
            15 & 16
        \end{array} \right]
    \end{array} \right]
    & = &
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4 \\
            9 & 10 \\
            11 & 12
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8 \\
            13 & 14 \\
            15 & 16
        \end{array} \right]
    \end{array} \right] \\
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8
        \end{array} \right]
    \end{array} \right]
    \oplus_2
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            9 & 10 \\
            11 & 12
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            13 & 14 \\
            15 & 16
        \end{array} \right]
    \end{array} \right]
    & = &
    \left[ \begin{array}{c}
        \left[ \begin{array}{cc}
            1 & 2 & 9 & 10 \\
            3 & 4 & 11 & 12
        \end{array} \right] \\
        \left[ \begin{array}{cc}
            5 & 6 & 13 & 14 \\
            7 & 8 & 15 & 16
        \end{array} \right]
    \end{array} \right]
\end{eqnarray}
$$

In [ ]:
tsr_1 = np.array([ [ [1, 2],
                     [3, 4] ],
                   [ [5, 6],
                     [7, 8] ] ])

tsr_2 = np.array([ [ [ 9, 10],
                     [11, 12] ],
                   [ [13, 14],
                     [15, 16] ] ])

print(f'concatenate(A, B) on axis 0 =\n{np.concatenate((tsr_1, tsr_2), axis=0)}\n')
print(f'concatenate(A, B) on axis 1 =\n{np.concatenate((tsr_1, tsr_2), axis=1)}\n')
print(f'concatenate(A, B) on axis 2 =\n{np.concatenate((tsr_1, tsr_2), axis=2)}\n')

concatenate(A, B) on axis 0 =
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]

concatenate(A, B) on axis 1 =
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]

concatenate(A, B) on axis 2 =
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]



### Tensor Norm

- We can compute the norm of a tensor by the command `la.norm`.

In [ ]:
tsr_a = np.array([ [ [1, 2],
                     [3, 4] ],
                   [ [5, 6],
                     [7, 8] ] ])
print(f'Matrix A =\n{tsr_a}\n')
print(f'Norm = {la.norm(tsr_b)}')

Matrix A =
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Norm = 38.67815921162743


- We can also compute the norm by projection on a particular axis by specifying the argument `axis`.

In [ ]:
print(f'Matrix A =\n{tsr_a}\n')

print(f'norm on axis 0 =\n{la.norm(tsr_a, axis=0)}')
print(f'norm on axis 1 =\n{la.norm(tsr_a, axis=1)}')
print(f'norm on axis 2 =\n{la.norm(tsr_a, axis=2)}')

Matrix A =
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

norm on axis 0 =
[[5.09901951 6.32455532]
 [7.61577311 8.94427191]]
norm on axis 1 =
[[ 3.16227766  4.47213595]
 [ 8.60232527 10.        ]]
norm on axis 2 =
[[ 2.23606798  5.        ]
 [ 7.81024968 10.63014581]]


### Addition and Subtraction

- We use `+` and `-`, respectively.

In [ ]:
tsr_a = np.array([ [ [1, 2],
                     [3, 4] ],
                   [ [5, 6],
                     [7, 8] ] ])

tsr_b = np.array([ [ [9, 10],
                     [11, 12] ],
                   [ [13, 14],
                     [15, 16] ] ])

print(f'A + B =\n{tsr_a + tsr_b}\n')
print(f'B - A =\n{tsr_b + tsr_a}')

A + B =
[[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]

B - A =
[[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]


### Scalar Multiplication

- We use the operator `*`.

In [ ]:
print(f'4 * A =\n{4 * tsr_a}')

4 * A =
[[[ 4  8]
  [12 16]]

 [[20 24]
  [28 32]]]


### Transpose

- The transpose of a tensor is the reverse of the dimensions of such tensor.
- For example, let's consider a rank-3 tensor $\mathbf{A}$, whose each element is addressed by $A_{ijk}$.
- The transpose of $ \mathbf{A} $, denoted by $\mathbf{A}^\top$, is defined as follows.
$$
\begin{eqnarray}
    \left[ \mathbf{A}^\top \right]_{kji} & = & A_{ijk}
\end{eqnarray}
$$

In [ ]:
print(f'A =\n{tsr_a}\n')

print(f'transpose(A) =\n{tsr_a.T}')

# For example, transpose(A)[0, 0, 1] = A[1, 0, 0] = 5

A =
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

transpose(A) =
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


- We can also permute the order of dimensions by the method `transpose`. 
- For example, we can permute the dimension order from (0, 1, 2) to (1, 0, 2) by `transpose((1, 0, 2))`

In [ ]:
print(f'transpose(A, (1, 0, 2)) =\n{tsr_a.transpose((1, 0, 2))}')

# For example, tranpose(A, (1, 0, 2))[11, 12, 13] = A[12, 11, 13]

transpose(A, (1, 0, 2)) =
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### Tensor Operations via Broadcasting

- An operation of two tensors is based on broadcasting, where any tensor of size greater than two dimensions is treated as a collection of data batches.
- There are two cases of broadcasting in tensors.

- <font color=blue>**Case 1:**</font> Tensor $\mathbf{A} = \left( 
    \mathbf{A}_1, \mathbf{A}_2, \mathbf{A}_3, \ldots, \mathbf{A}_n
\right)$, when applied on matrix $\mathbf{M}$, is equal to broadcasting such operation of $\mathbf{M}$ to each batch $\mathbf{A}_k$ in $\mathbf{A}$. That is:
$$
\begin{eqnarray}
\mathbf{A} \circ \mathbf{M} & = & \left(
    \mathbf{A}_1 \circ \mathbf{M}, \mathbf{A}_2  \circ \mathbf{M}, \mathbf{A}_3  \circ \mathbf{M}, \ldots, \mathbf{A}_n \circ \mathbf{M}
\right)
\end{eqnarray}
$$
where $\circ$ is a binary operation.

In [ ]:
tsr_a = np.array([ [ [ [1, 2],
                       [3, 4] ],
                     [ [5, 6],
                       [7, 8] ] ],
                   [ [ [9, 10],
                       [11, 12] ],
                     [ [13, 14],
                       [15, 16] ] ] ])

tsr_b = np.array([ [0, 1],
                   [1, 0] ])

tsr_a @ tsr_b

array([[[[ 2,  1],
         [ 4,  3]],

        [[ 6,  5],
         [ 8,  7]]],


       [[[10,  9],
         [12, 11]],

        [[14, 13],
         [16, 15]]]])

- <font color=blue>**Case 2:**</font> Tensor $\mathbf{A} = \left( \mathbf{A}_1, \mathbf{A}_2, \mathbf{A}_3, \ldots, \mathbf{A}_n \right)$, when applied on tensor $\mathbf{B} = \left( \mathbf{B}_1, \mathbf{B}_2, \mathbf{B}_3, \ldots, \mathbf{B}_n \right)$, is equal to broadcasting such operation of each corresponding batch pair $\mathbf{A}_k \times \mathbf{B}_k$. That is:
$$
\begin{eqnarray}
\mathbf{A} \circ \mathbf{B} & = & \left(
    \mathbf{A}_1 \circ \mathbf{B}_2, \mathbf{A}_2 \circ \mathbf{B}_2, \mathbf{A}_3 \circ \mathbf{B}_3, \ldots, \mathbf{A}_n \circ \mathbf{B}_n
\right)
\end{eqnarray}
$$
where $\circ$ is a binary operation.

In [ ]:
# There are two batches in A, divided by the first dimension
tsr_a = np.array([ [ [ [1, 2],
                       [3, 4] ],
                     [ [5, 6],
                       [7, 8] ] ],
                   [ [ [9, 10],
                       [11, 12] ],
                     [ [13, 14],
                       [15, 16] ] ] ])

# There are also two batches in B
tsr_b = np.array([ [ [1, 0],
                     [0, 1] ],
                   [ [0, 1],
                     [1, 0] ] ])

tsr_a @ tsr_b

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 6,  5],
         [ 8,  7]]],


       [[[ 9, 10],
         [11, 12]],

        [[14, 13],
         [16, 15]]]])

- **N.B.** Note that two tensors of difference batch sizes cannot be multiplied due to shape mismatch.

In [ ]:
# There are two batches in A
tsr_a = np.array([ [ [1, 2],
                     [3, 4] ],
                   [ [5, 6],
                     [7, 8] ] ])

# There are three batches in B
tsr_b = np.array([ [ [1, 0],
                     [0, 1] ],
                   [ [1, 0],
                     [0, 1] ],
                   [ [0, 1],
                     [1, 0] ] ])

# Running this will cause an exception
# tsr_a @ tsr_b

-----
## Exercises 4

### Question 4.1

Let's create a rank-5 tensor $\mathbf{C}$ containing the numbers starting from 1 to 32. Observe how `numpy` prints it out. How many blank lines are used to separate each dimension?

In [ ]:
# tsr_c = np.zeros((2, 2, 2, 2, 2))          # Rank-5 tensor
# 
# for i1 in range(2):
#     for i2 in range(2):
#         for i3 in range(2):
#             for i4 in range(2):
#                 for i5 in range(2):
#                     tsr_c[i1, i2, i3, i4, i5] = __________
# 
# print(tsr_c)

#### Solution

In [ ]:
tsr_c = np.zeros((2, 2, 2, 2, 2))          # Rank-5 tensor

for i1 in range(2):
    for i2 in range(2):
        for i3 in range(2):
            for i4 in range(2):
                for i5 in range(2):
                    tsr_c[i1, i2, i3, i4, i5] = \
                        16 * i1 + 8 * i2 + 4 * i3 + 2 * i4 + i5 + 1

print(tsr_c)

[[[[[ 1.  2.]
    [ 3.  4.]]

   [[ 5.  6.]
    [ 7.  8.]]]


  [[[ 9. 10.]
    [11. 12.]]

   [[13. 14.]
    [15. 16.]]]]



 [[[[17. 18.]
    [19. 20.]]

   [[21. 22.]
    [23. 24.]]]


  [[[25. 26.]
    [27. 28.]]

   [[29. 30.]
    [31. 32.]]]]]


### Question 4.2

Write down a matrix representation of tensor $\mathbf{C}$ on a sheet of paper. Observe how batches of matrices are organized.

#### Solution

$$
\left[ \begin{array}{cc}
    \left[ \begin{array}{cc}
        \left[ \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array}\right]
        &
        \left[ \begin{array}{cc}
            5 & 6 \\
            7 & 8
        \end{array}\right]
        \\
        \left[ \begin{array}{cc}
            9 & 10 \\
            11 & 12
        \end{array}\right]
        &
        \left[ \begin{array}{cc}
            13 & 14 \\
            15 & 16
        \end{array}\right]
    \end{array} \right]
    \\
    \left[ \begin{array}{cc}
        \left[ \begin{array}{cc}
            17 & 18 \\
            19 & 20
        \end{array}\right]
        &
        \left[ \begin{array}{cc}
            21 & 22 \\
            23 & 24
        \end{array}\right]
        \\
        \left[ \begin{array}{cc}
            25 & 26 \\
            27 & 28
        \end{array}\right]
        &
        \left[ \begin{array}{cc}
            29 & 30 \\
            31 & 32
        \end{array}\right]
    \end{array} \right]
\end{array} \right]
$$

### Question 4.3

**Power Method** is an algorithm that computes the dominant eigenvector (the eigenvector whose eigenvalue is the largest) of a square matrix. The basic idea of the Power Method is quite simple. For a given square matrix $\mathbf{M}$:

  1. Let $\mathbf{v}^{(0)}$ be an arbitrary unit vector.
  2. For each $k$-th iteration
    1. We multiply $\mathbf{M}$ by an unit vector $\mathbf{v}^{(k)}$ to obtain a new vector $\mathbf{v}^{(k + 1)}$.
    2. We normalize $\mathbf{v}^{(k + 1)}$.
  3. We repeat the loop in Step 2 until $\mathbf{v}^{(k + 1)}$ becomes convergent.
  4. The resulted vector becomes the dominant eigenvector of $\mathbf{M}$.

In this exercise, we will implement the Power Method with NumPy step by step.

### Question 4.3.1

Implement a function that normalizes an input vector. It should return a unit vector as a result.
$$
\begin{eqnarray}
    \mathrm{normalize}(\mathbf{v}) & = & \frac{\mathbf{v}}{\left\| \mathbf{v} \right\|}
\end{eqnarray}
$$

In [ ]:
# def normalize(vec):
#     return ___________          # Fill in this blank.

#### Solution

In [ ]:
def normalize(vec):
    return vec / la.norm(vec)

### Question 4.3.2

Implement a function that checks whether two <u>unit</u> vectors converge or not. In this exercise, vectors $\mathbf{v}_1$ and $\mathbf{v}_2$ are said to converge to each other if their Euclidean distance is less than the given threshold.
$$
\begin{eqnarray}
    \mathrm{dist}(\mathbf{v}_1, \mathbf{v}_2) & = & \left\| \mathbf{v}_1 - \mathbf{v}_2 \right\|
\end{eqnarray}
$$
This function should return a boolean value indicating if $\mathbf{v}_1$ and $\mathbf{v}_2$ converge to each other or not.

In [ ]:
# def is_converge(vec1, vec2, threshold):
#     
#     # Compute the Euclidean distance between vec1 and vec2.
#     dist = __________
#     
#     # Return the boolean value that indicates the convergence with respect to the given threshold.
#     return __________

#### Solution

In [ ]:
def is_converge(vec1, vec2, threshold):
    
    # Compute the Euclidean distance between vec1 and vec2.
    dist = la.norm(vec1 - vec2)
    
    # Return the boolean value that indicates the convergence with respect to the given threshold.
    return dist < threshold

### Question 4.3.3

Implement a function that computes the dominant eigenvector of a given square matrix $\mathbf{M}$. Read the instruction in the comments carefully and follow it accordingly.

In [ ]:
# def power_method(matrix, threshold, maxiters):
#     
#     # Find the first dimension of the given matrix.
#     dim = __________
#     
#     # Randomize an arbitrary unit vector using rnd.randn. This is your v^(0).
#     # Don't forget to normalize it before use.
#     vec = __________
#     
#     # Iterative Power Method
#     for i in range(maxiters):
#         
#         # Multiply the given matrix with vec and normalize the result.
#         newvec = __________
#         
#         # If the obtained vector and the old vector converge, stop the iteration.
#         if is_converge(vec, newvec, threshold):
#             break
#             
#         # Otherwise, keep the obtained vector and continue the iteration.
#         else:
#             vec = newvec
#             
#     return newvec

#### Solution

In [ ]:
def power_method(matrix, threshold, maxiters):
    
    # Find the first dimension of the given matrix.
    dim = matrix.shape[0]
    
    # Randomize an arbitrary unit vector using rnd.randn. This is your v^(0).
    # Don't forget to normalize it before use.
    vec = normalize(rnd.randn(dim))
    
    # Iterative Power Method
    for i in range(maxiters):
        
        # Multiply the given matrix with vec and normalize the result.
        newvec = normalize(matrix @ vec)
        
        # If the obtained vector and the old vector converge, stop the iteration.
        if is_converge(vec, newvec, threshold):
            break
            
        # Otherwise, keep the obtained vector and continue the iteration.
        else:
            vec = newvec
            
    return newvec

### Question 4.3.4

Implement a function that computes an eigenvalue $\lambda$ of an eigenvector $\mathbf{v}$ with respect to an input matrix $\mathbf{M}$. The eigenvalue can be computed with the Rayleigh quotient below.
$$
\begin{eqnarray}
    \lambda & = & \frac{\mathbf{v}^\top \mathbf{M} \mathbf{v}}{\mathbf{v}^\top \mathbf{v}}
\end{eqnarray}
$$

In [ ]:
# def rayleigh(matrix, vec):
#     return __________

#### Solution

In [ ]:
def rayleigh(matrix, vec):
    return (vec.T @ matrix @ vec) / (vec.T @ vec)

### Question 4.3.5

**Testing:** You can test your implementation with the following simple code.

In [ ]:
# m = np.array([ [ 1,  2,  3,  4],
#                [ 5,  6,  7,  8],
#                [ 9, 10, 11, 12],
#                [13, 14, 15, 16] ])
# 
# result = power_method(m, 1e-3, 100)
# 
# print(f'Eigenvector = {result}')
# print(f'Eigenvalue  = {rayleigh(m, result)}')

#### Solution

In [ ]:
m = np.array([ [ 1,  2,  3,  4],
               [ 5,  6,  7,  8],
               [ 9, 10, 11, 12],
               [13, 14, 15, 16] ])

result = power_method(m, 1e-3, 100)

print(f'Eigenvector = {result}')
print(f'Eigenvalue  = {rayleigh(m, result)}')

Eigenvector = [-0.15113875 -0.34922934 -0.54731993 -0.74541052]
Eigenvalue  = 36.209118843212956


-----
## 5. Custom Array Construction

- Instead of keying in all numbers when creating a new array, there are several useful functions that create an array of your desire.

### `np.arange(a, b, step)`

- Create a vector starting from `a` to `b` with the stepping size `step`.
- This command is similar to `range` used in the for-loop. 
- For example, `np.arange(1, 10, 1)` creates an array $[1, 2, 3, \ldots, 9]$.

In [ ]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- We can determine the step size by changing the last argument.

- For example, `np.arange(1, 10, 2)` creates an array $[1, 3, 5, 7, 9]$.

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

- If we set the step size to a negative value, the series will go descendingly.

- For example, `np.arange(10, 0, -1)` creates an array $[10, 9, 8, \ldots, 1]$.

In [ ]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### `np.linspace(a, b, num)`

- Create a vector starting from `a` to `b` with the specified number of elements `num` (including the start and the end).
- `linspace` is short for 'linear space'.
- For example, `np.linspace(1, 10, 7)` creates an array $[1, 2.5, 4, 5.5, 7, 8.5, 10]$.

In [ ]:
np.linspace(1, 10, 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

### Array Reshaping

- Once you create an array, you can reshape it to become a matrix or a tensor with the method `reshape`. 
- For example, we can reshape the array $[1, 2, 3, \ldots, 9]$ to become a matrix of shape (3, 3):

$$
\left[ \begin{array}{ccc}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9 
\end{array} \right]
$$

In [ ]:
vec9 = np.arange(1, 10, 1)
print(f'As a vector:\n{vec9}\n')
mat9 = vec9.reshape(3, 3)
print(f'As a matrix:\n{mat9}')

As a vector:
[1 2 3 4 5 6 7 8 9]

As a matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Array Flattening

- We can flatten a tensor by the command `np.ravel`.

In [ ]:
mat9.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Side Effects of Element Setting in Array Reshaping

- Note that array reshaping does not copy the content of the array.
- We can therefore reshape an array efficiently at any point.
- However, bear in mind that array manipulation has a side effect on any reshaping, too.
- In the below example, changing a cell in any reshape will affect the original content and any of its reshapes, too.

In [ ]:
print('BEFORE\n')
vec16 = np.arange(1, 17, 1)
print(f'As a vector:\n{vec16}\n')
mat16 = vec16.reshape(4, 4)
print(f'As a matrix:\n{mat16}\n')
tsr242 = mat16.reshape(2, 4, 2)
print(f'As a (2,4,2)-tensor:\n{tsr242}\n')
tsr2222 = tsr242.reshape(2, 2, 2, 2)
print(f'As a (2,2,2,2)-tensor:\n{tsr2222}\n')

tsr2222[0, 1, 1, 0] = 100

print('AFTER\n')
print(f'As a vector:\n{vec16}\n')
print(f'As a matrix:\n{mat16}\n')
print(f'As a (2,4,2)-tensor:\n{tsr242}\n')
print(f'As a (2,2,2,2)-tensor:\n{tsr2222}\n')

BEFORE

As a vector:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

As a matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

As a (2,4,2)-tensor:
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]

As a (2,2,2,2)-tensor:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]

AFTER

As a vector:
[  1   2   3   4   5   6 100   8   9  10  11  12  13  14  15  16]

As a matrix:
[[  1   2   3   4]
 [  5   6 100   8]
 [  9  10  11  12]
 [ 13  14  15  16]]

As a (2,4,2)-tensor:
[[[  1   2]
  [  3   4]
  [  5   6]
  [100   8]]

 [[  9  10]
  [ 11  12]
  [ 13  14]
  [ 15  16]]]

As a (2,2,2,2)-tensor:
[[[[  1   2]
   [  3   4]]

  [[  5   6]
   [100   8]]]


 [[[  9  10]
   [ 11  12]]

  [[ 13  14]
   [ 15  16]]]]



### `np.fromfunction(fn, shape)`

- Create a tensor of the specified shape `shape` using the specified function `fn`.

In [ ]:
def fn(x, y):
    return (x * y + 1) / (x + y + 1)

# The below command is equivalent to the following code.
# mat_d = np.zeros((5, 3))
# for i in range(5):
#     for j in range(3):
#         mat_d[i, j] = fn(i, j)
mat_d = np.fromfunction(fn, (5, 3))
print(mat_d)

[[1.         0.5        0.33333333]
 [0.5        0.66666667 0.75      ]
 [0.33333333 0.75       1.        ]
 [0.25       0.8        1.16666667]
 [0.2        0.83333333 1.28571429]]


-----
## Exercises 5

### Question 5.1

**The Cube of Numbers:** Receive an integer $n$ from the user and create a 3-dimensional tensor containing the numbers starting from 1 to $n^3$. The one-liner way to solve this problem is to use `np.arange` and `reshape`. For example, 

```
    Enter n: 3
    [[[ 1  2  3]
      [ 4  5  6]
      [ 7  8  9]]

     [[10 11 12]
      [13 14 15]
      [16 17 18]]

     [[19 20 21]
      [22 23 24]
      [25 26 27]]]
```

In [ ]:
# # Receive an integer from the user.
# n = int(input('Enter n: '))
# 
# # Construct a 3-D tensor containing 1 to n**3.
# tensor = __________       # Fill in this blank.
# 
# # Print it out.
# print(tensor)

#### Solution

In [ ]:
# Receive an integer from the user.
n = 10     # Please change it to `input` in the answer box.

# Construct a 3-D tensor containing 1 to n**3.
tensor = 1 + np.arange(n ** 3).reshape(n, n, n)

# Print it out.
print(tensor)

[[[   1    2    3    4    5    6    7    8    9   10]
  [  11   12   13   14   15   16   17   18   19   20]
  [  21   22   23   24   25   26   27   28   29   30]
  [  31   32   33   34   35   36   37   38   39   40]
  [  41   42   43   44   45   46   47   48   49   50]
  [  51   52   53   54   55   56   57   58   59   60]
  [  61   62   63   64   65   66   67   68   69   70]
  [  71   72   73   74   75   76   77   78   79   80]
  [  81   82   83   84   85   86   87   88   89   90]
  [  91   92   93   94   95   96   97   98   99  100]]

 [[ 101  102  103  104  105  106  107  108  109  110]
  [ 111  112  113  114  115  116  117  118  119  120]
  [ 121  122  123  124  125  126  127  128  129  130]
  [ 131  132  133  134  135  136  137  138  139  140]
  [ 141  142  143  144  145  146  147  148  149  150]
  [ 151  152  153  154  155  156  157  158  159  160]
  [ 161  162  163  164  165  166  167  168  169  170]
  [ 171  172  173  174  175  176  177  178  179  180]
  [ 181  182  183  184  18

### Question 5.2

Suppose you want plot a line chart representing a growth trend of virus colonies against the number of days in the incubation period. Create two vectors for the X and Y axes, where:
  - The X axis shows the number of days, ranging from 0 to 20 (days), and increasing 1 at a time.
  - The Y axis shows the total area of virus colonies in the cultured dish, ranging from 0 to 50.0 (cm squared), and containing 8 steps.

In [ ]:
# x_axis = __________          # Fill in these blanks.
# y_axis = __________
# 
# print(f'X axis:\n{x_axis}\n')
# print(f'Y axis:\n{y_axis}\n')

#### Solution

In [ ]:
x_axis = np.arange(0, 21, 1)
y_axis = np.linspace(0, 50.0, 8)

print(f'X axis:\n{x_axis}\n')
print(f'Y axis:\n{y_axis}\n')

X axis:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Y axis:
[ 0.          7.14285714 14.28571429 21.42857143 28.57142857 35.71428571
 42.85714286 50.        ]



-----
## 6. Boolean Operations on Array

### First Order Logic

- We can apply boolean operations on any array, resulting in an array of truth values of the same shape, called *condition*.

In [ ]:
mat_a = rnd.randn(5, 3)
print(f'Matrix A =\n{mat_a}\n')

cond_1 = (mat_a >= 0.25)
print(f'Condition = (A >= 0.25)\n{cond_1}\n')

Matrix A =
[[ 0.4318635   1.0179049   0.96878504]
 [ 0.62966601 -0.40596231 -0.90399958]
 [ 0.38883351  0.36775205  1.16022877]
 [ 0.70685026  0.16498106 -0.60437115]
 [-0.20066382 -2.7954708   0.14005175]]

Condition = (A >= 0.25)
[[ True  True  True]
 [ True False False]
 [ True  True  True]
 [ True False False]
 [False False False]]



- We can also add bit-wise logical connectives `&` (and), `|` (or), `^` (exclusive or), and `~` (not) in a logical expression containing arrays. 
- Do not use the traditional logical connectives `and`, `or`, and `not` as they will cause errors.
- Note that we always use parentheses each operand of these connectives. 

In [ ]:
# Note that you cannot use Python's chained syntax -0.25 <= mat_a <= 0.25.
cond_2 = (mat_a >= -0.25) & (mat_a <= 0.25)
print(f'Condition = (-0.25 <= A <= 0.25)\n{cond_2}\n')

Condition = (-0.25 <= A <= 0.25)
[[False False False]
 [False False False]
 [False False False]
 [False  True False]
 [ True False  True]]



- We can count the number of elements that satisfy the logical expression via the command `np.sum`. The command counts `True` as 1 and `False` as 0, respectively.

In [ ]:
np.sum(cond_2)

3

- Logical quantifiers such as `np.any` (for some) and `np.all` (for all) can also be applied to the boolean operations to obtain a final truth value.

In [ ]:
print(f'Any element of A is in [-0.25, 0.25] = {np.any(cond_2)}')
print(f'All element of A is in [-0.25, 0.25] = {np.all(cond_2)}')

Any element of A is in [-0.25, 0.25] = True
All element of A is in [-0.25, 0.25] = False


- You can also specify the projection axis of `np.any` and `np.all` with the argument `axis`.

In [ ]:
print(f'Any element of A is in [-0.25, 0.25] = {np.any(cond_2, axis=0)}')
print(f'All element of A is in [-0.25, 0.25] = {np.all(cond_2, axis=1)}')

Any element of A is in [-0.25, 0.25] = [ True  True  True]
All element of A is in [-0.25, 0.25] = [False False False False False]


### Boolean Masking

- We can extract the elements whose truth values are `True` by simple indexing.

In [ ]:
mat_a = rnd.randn(5, 3)
print(f'Matrix A =\n{mat_a}\n')

cond_1 = (-0.25 <= mat_a) & (mat_a <= 0.25)
print(f'Condition = (-0.25 <= A <= 0.25)\n{cond_1}\n')

print(f'Masking A with Condition =\n{mat_a[cond_1]}')

Matrix A =
[[-2.2326922   1.68368845  1.57492975]
 [-0.86672628 -0.78876608 -0.90330632]
 [-0.66665993  0.57857384  0.57259997]
 [ 1.54229521 -0.34800782  0.81806801]
 [-0.84086511 -0.81162515  0.25111412]]

Condition = (-0.25 <= A <= 0.25)
[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]

Masking A with Condition =
[]


- We can also set the elements whose truth values are `True` by indexing.

In [ ]:
mat_a[cond_1] = 0.0
print(mat_a)

[[-2.2326922   1.68368845  1.57492975]
 [-0.86672628 -0.78876608 -0.90330632]
 [-0.66665993  0.57857384  0.57259997]
 [ 1.54229521 -0.34800782  0.81806801]
 [-0.84086511 -0.81162515  0.25111412]]


### Conditional Array Creation

- We can create a new array out of two input arrays according to a given condition with the command `np.where`.
- Note that both input arrays must have the same shape.

In [ ]:
mat_a = rnd.randn(5, 3)
print(f'Matrix A =\n{mat_a}\n')

cond_1 = (-0.25 <= mat_a) & (mat_a <= 0.25)
print(f'Condition = (-0.25 <= A <= 0.25)\n{cond_1}\n')

mat_c = rnd.randint(1, 10, (5, 3))
print(f'Matrix C =\n{mat_a}\n')

mat_d = rnd.randint(11, 20, (5, 3))
print(f'Matrix D =\n{mat_b}\n')

# For each element of cond_1:
#     If that element of cond_1 is True, choose the corresponding element from C
#     Otherwise, choose the corresponding element from D instead
result = np.where(cond_1, mat_c, mat_d)
print(f'Result = where(Condition, C, D)\n{result}')

Matrix A =
[[ 0.34801784  0.91470975  0.30786647]
 [ 1.41702782 -0.03590942 -0.69905877]
 [ 0.15874183  1.32961692  0.44075189]
 [ 0.76497151  0.99304885  0.29039127]
 [ 0.92332538 -0.18698614  0.84843501]]

Condition = (-0.25 <= A <= 0.25)
[[False False False]
 [False  True False]
 [ True False False]
 [False False False]
 [False  True False]]

Matrix C =
[[ 0.34801784  0.91470975  0.30786647]
 [ 1.41702782 -0.03590942 -0.69905877]
 [ 0.15874183  1.32961692  0.44075189]
 [ 0.76497151  0.99304885  0.29039127]
 [ 0.92332538 -0.18698614  0.84843501]]

Matrix D =
[[ 0.15436301  0.2682579   1.17731929]
 [-0.06900565  0.02453535 -0.01564794]]

Result = where(Condition, C, D)
[[18 11 11]
 [11  3 18]
 [ 1 17 16]
 [14 19 19]
 [17  3 15]]


-----
## Exercises 6

In this exercise, we are going to observe some behaviors of *pseudo-randomization*. That is, we are wondering if we can find any patterns in these random numbers. One way to do so is we will generate a sequence of some random numbers and observe its accumulated positivity through the sequence.

For example, suppose we have a sequence of random numbers:

$$
[0.1, -0.75, 0.9, 1.7, -0.9, -2.5, 0.05, 0.7, 1.9, -2.1, -0.3, -0.1]
$$

At first glance, we do not see any patterns in these random numbers.

To unveil the pattern, we observe the positive accumulator. For each number in the sequence, we increase the posive accumulator by 1 if it is a positive number, and decrease the accumulator by 1 if it is a negative number. If we observe the change in the accumulator, we can now see the following pattern.

$$
[1, 0, 1, 2, 1, 0, 1, 2, 3, 2, 1, 0]
$$

### Question 6.1

Implement this process in the following code.

In [ ]:
# # Number of random numbers
# no_nums = 400
# 
# # Generate a random vector a of dimension [no_nums].
# vec_a = __________
# 
# # Create a zero vector of dimension [no_nums].
# result = __________
# 
# # Accumulator
# acc = 0.0
# for i in range(no_nums):
#     # If each element in vector a is greater or equal to 0, then increase the accumulator.
#     if __________ :
#         acc += 1
#     # Otherwise, decreate the accumulator.
#     else:
#         acc -= 1
#     # Save the value of the accumulator to result.
#     result[i] = acc
#     
# print(f'Result:\n{result}\n')
# 
# # Count the number of zeros in the result.
# print(f'Number of zeros = { __________ }')

#### Solution

In [ ]:
# Number of random numbers
no_nums = 400

# Generate a random vector a of dimension [no_nums].
vec_a = rnd.randn(no_nums)

# Create a zero vector of dimension [no_nums].
result = np.zeros(no_nums)

# Accumulator
acc = 0.0
for i in range(no_nums):
    # If each element in vector a is greater or equal to 0, then increase the accumulator.
    if vec_a[i] >= 0:
        acc += 1
    # Otherwise, decreate the accumulator.
    else:
        acc -= 1
    # Save the value of the accumulator to result.
    result[i] = acc
    
print(f'Result:\n{result}\n')

# Count the number of zeros in the result.
print(f'Number of zeros = { (result == 0).sum() }')

Result:
[ -1.  -2.  -3.  -2.  -3.  -2.  -1.  -2.  -3.  -4.  -3.  -2.  -1.   0.
   1.   2.   1.   2.   3.   2.   1.   2.   3.   4.   3.   4.   3.   2.
   1.   0.   1.   0.  -1.  -2.  -1.   0.  -1.  -2.  -3.  -4.  -3.  -4.
  -3.  -2.  -3.  -2.  -3.  -2.  -3.  -2.  -1.   0.  -1.   0.  -1.   0.
   1.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -5.  -6.  -5.  -4.
  -3.  -4.  -3.  -2.  -1.   0.  -1.  -2.  -3.  -2.  -1.   0.   1.   0.
   1.   0.  -1.  -2.  -3.  -4.  -3.  -2.  -3.  -4.  -3.  -4.  -5.  -4.
  -3.  -4.  -5.  -6.  -5.  -6.  -7.  -8.  -9.  -8.  -7.  -8.  -9. -10.
 -11. -10. -11. -12. -11. -12. -11. -12. -11. -12. -11. -12. -11. -12.
 -11. -12. -13. -14. -13. -12. -11. -10.  -9.  -8.  -7.  -6.  -5.  -4.
  -3.  -2.  -3.  -4.  -5.  -4.  -3.  -4.  -3.  -2.  -3.  -2.  -1.   0.
  -1.  -2.  -1.  -2.  -3.  -2.  -1.  -2.  -3.  -2.  -3.  -4.  -5.  -6.
  -5.  -4.  -5.  -4.  -5.  -6.  -7.  -8.  -9.  -8.  -7.  -8.  -7.  -8.
  -7.  -8.  -9.  -8.  -9.  -8.  -7.  -8.  -7.  -6.  -7.  -8.  -7.  -6

### Question 6.2

Try different numbers of random numbers `no_nums` and observe the patterns.

### Question 6.3

What does the number of zeros tell us about the patterns?

-----
## 7. Useful Functions on Array

### Summation

- We can compute the summation of all elements in an array by the command `np.sum()`.
- If the argument `axis` is determined, the summation will be computed on such axis; i.e. the summation is projected on that axis.

In [ ]:
mat_a = np.array([ [ 1,  2,  3,  4,  5],
                   [ 6,  7,  8,  9, 10],
                   [11, 12, 13, 14, 15] ])

print(f'Matrix A =\n{mat_a}\n')

sum_all = np.sum(mat_a)
print(f'Summation of all elements = {sum_all}')

sum_0 = np.sum(mat_a, axis=0)
print(f'Summation on axis 0 (row) = {sum_0}')

sum_1 = np.sum(mat_a, axis=1)
print(f'Summation on axis 1 (column) = {sum_1}')

Matrix A =
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Summation of all elements = 120
Summation on axis 0 (row) = [18 21 24 27 30]
Summation on axis 1 (column) = [15 40 65]


### Aggregation

- We can compute aggregation functions, e.g. `np.max`, `np.min`, `np.average`, `np.median`, `np.argmax`, and `np.argmin`, on an array as well.
- If the argument `axis` is determined, the computation will be projected on such axis.

In [ ]:
mat_a = np.array([ [ 1,  2,  3,  4,  5],
                   [10,  9,  8,  7,  6],
                   [11, 12, 13, 14, 15] ])

print(f'Matrix A =\n{mat_a}\n')

max_elem = np.max(mat_a)
min_elem = np.min(mat_a)
print(f'Maximum element = {max_elem}')
print(f'Minimum element = {min_elem}\n')

avg_elem = np.average(mat_a)
avg_1 = np.average(mat_a, axis=0)
avg_2 = np.average(mat_a, axis=1)
print(f'Average = {avg_elem}')
print(f'Average on axis 0 (row) = {avg_1}')
print(f'Average on axis 1 (column) = {avg_2}\n')

med_elem = np.median(mat_a)
med_1 = np.median(mat_a, axis=0)
med_2 = np.median(mat_a, axis=1)
print(f'Median = {med_elem}')
print(f'Median on axis 0 (row) = {med_1}')
print(f'Median on axis 1 (column) = {med_2}\n')

# argmax and argmin return the maximum and minimum indices, respectively
argmax_1 = np.argmax(mat_a, axis=0)
argmin_2 = np.argmin(mat_a, axis=1)
print(f'Argmax on axis 0 (row) = {argmax_1}')
print(f'Argmin on axis 1 (column) = {argmin_2}')

Matrix A =
[[ 1  2  3  4  5]
 [10  9  8  7  6]
 [11 12 13 14 15]]

Maximum element = 15
Minimum element = 1

Average = 8.0
Average on axis 0 (row) = [7.33333333 7.66666667 8.         8.33333333 8.66666667]
Average on axis 1 (column) = [ 3.  8. 13.]

Median = 8.0
Median on axis 0 (row) = [10.  9.  8.  7.  6.]
Median on axis 1 (column) = [ 3.  8. 13.]

Argmax on axis 0 (row) = [2 2 2 2 2]
Argmin on axis 1 (column) = [0 4 0]


### Cumulative Summation

- We can compute the cumulative summation on each index by the command `np.cumsum`. 
- The argument `axis` is also available for axis projection.

In [ ]:
mat_b = np.array([ [ 0,  1,  2,  3],
                   [ 4,  5,  6,  7],
                   [ 8,  9, 10, 11],
                   [12, 13, 14, 15],
                   [16, 17, 18, 19],
                   [20, 21, 22, 23] ])
print(f'Matrix B:\n{mat_b}\n')

cumsum_1 = np.cumsum(mat_b, axis=0)
cumsum_2 = np.cumsum(mat_b, axis=1)
print(f'Cumulative summation on axis 0 (row) =\n{cumsum_1}\n')
print(f'Cumulative summation on axis 1 (column) =\n{cumsum_2}')

Matrix B:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Cumulative summation on axis 0 (row) =
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]
 [40 45 50 55]
 [60 66 72 78]]

Cumulative summation on axis 1 (column) =
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]
 [12 25 39 54]
 [16 33 51 70]
 [20 41 63 86]]


### Sampling

- We can draw some samples from an item collection based on a probability distribution of each item with the command `rnd.choice(collection, size, p)`. 
- The argument `p` is a uniform distribution by default.

In [ ]:
words    = ['hello', 'world', 'prachya', 'boonkwan']
probdist = [   0.15,    0.30,      0.25,       0.30]

samples_uniform = rnd.choice(words, 5)
print(f'5 samples from a uniform distribution: {samples_uniform}')

samples_word = rnd.choice(words, 5, p=probdist)
print(f'5 samples from a predefined distribution: {samples_word}')

5 samples from a uniform distribution: ['hello' 'prachya' 'boonkwan' 'world' 'boonkwan']
5 samples from a predefined distribution: ['prachya' 'boonkwan' 'world' 'boonkwan' 'world']


-----
## Exercises 7

The value of $\pi$ was discovered for more than 3,500 years. The constant $\pi$, as the Babylonians and the Egyptians understood, is the ratio between a circle's diameter and its circumference. In the ancient Greek time, mathematician Archimedes of Syracuse (287-212 BC) is widely accepted to be the first to compute the value of $\pi$. He did not calculate its exact value. However, he approximated its close value by inscribing a circle between a $n-1$ polygon and another $n$ polygon and compute the upper and lower bounds of the value of $\pi$.

In this exercise, we will approximate the value of $\pi$ via simple simulation. Imagine we have a circle inscribed in a square.

<center>![A circle inscribed in a square](https://www.varsitytutors.com/assets/vt-hotmath-legacy/hotmath_help/topics/circles-inscribed-in-squares/lesson1.gif)</center>

Suppose the circle's radius is $r$, the area of the circle is $\pi r^2$, while the area of the inscribing square is $(2r)^2 = 4 r^2$. We obtain that

$$
\begin{eqnarray}
    \frac{\textrm{Area of circle}}{\textrm{Area of square}} & = & \frac{\pi r^2}{4 r^2} \\
    \therefore \quad \pi & = & 4 \times \frac{\textrm{Area of circle}}{\textrm{Area of square}}
\end{eqnarray}
$$

Now we have come to the question of approximating the area of a circle. We can do so with simulation. The probability of a random point being inside the circle given that the point is already inside the square is:

$$
\begin{eqnarray}
    P(\textrm{inside circle} | \textrm{inside square}) & \approx & \frac{P(\textrm{inside circle}, \textrm{inside square})}{P(\textrm{inside square})} \\
    & = & \frac{\#(\textrm{inside circle}, \textrm{inside square})}{\#(\textrm{inside square})}
\end{eqnarray}
$$

where $\#$ is the frequency of random points of such condition.

By combining the results of above derivation, we obtain that:

$$
\begin{eqnarray}
    \pi & = & 4 \times \frac{\textrm{Area of circle}}{\textrm{Area of square}} \\
    & \approx & 4 \times  \frac{\#(\textrm{inside circle}, \textrm{inside square})}{\#(\textrm{inside square})}
\end{eqnarray}
$$

We will approximate the value of $\pi$ via this simulation method.

### Question 7.1

Implement a function that checks if each row vector in the input matrix $\mathbf{M}$ is in a circle with the radius of $r$. We say that a vector $\mathbf{v}$ is in that circle if the vector's norm $\left\| \mathbf{v} \right\| \leq r$.

In [ ]:
# def is_in_circle(vecs, radius):
#
#     # Find the norm of each row vector.
#     rownorms = __________
#
#     # Create a criterion for each row vector being in the circle of a specified radius.
#     criterion = __________
#
#     return criterion

#### Solution

In [ ]:
def is_in_circle(vecs, radius):
    
    # Find the norm of each row vector.
    rownorms = la.norm(vecs, axis=1)
    
    # Create a criterion for each row vector being in the circle of a specified radius.
    criterion = rownorms <= radius
    
    return criterion

### Question 7.2

Implement the following simulation method for the value of $\pi$.

  1. Suppose there is a circle whose diameter is 2 and it is inscribed in a square whose side is of length 2.

  2. Draw $N$ random points from a uniform distribution in the range of [-1, 1]
  
  3. Count the number of random points that are in the circle. Let's denote that number with $C$.
  
  4. Approximate the value of $\pi \approx \frac{C}{N}$.

In [ ]:
# # Let's set the number of random points.
# num_points = 100
# 
# # Random [num_points] random points of two dimensions.
# vecs = __________
# 
# # Check if each random point is in such circle using [is_in_circle].
# in_circle = __________
# 
# # Count the random points that are in the circle.
# count_in = __________
# 
# # Approximate the value of pi.
# pi_value = 4 * count_in / num_points
# 
# print(pi_value)

#### Solution

In [ ]:
# Let's set the number of random points.
num_points = 100000

# Random [num_points] random points of two dimensions.
vecs = rnd.uniform(-1, 1, (num_points, 2))

# Check if each random point is in such circle.
in_circle = is_in_circle(vecs, 1)

# Count the random points that are in the circle.
count_in = in_circle.sum()

# Approximate the value of pi.
pi_value = 4 * count_in / num_points

print(pi_value)

3.1396


-----
## 8. Sparse Matrices

- Furthermore, there are two types of matrices in NumPy: dense and sparse.
  - For the dense matrix, its entire content is stored as an array in the memory.
  - For the sparse matrix, only some parts of its content are stored in the memory to save some space.
- The latter type offers some space efficiency but may underperform in some mathematical operations and content manipulation.

- There are four popular sparse formats:
  1. Coordinate format (COO)
  2. Compressed sparse row (CSR)
  3. Compressed sparse column (CSC)
  4. Block sparse row (BSR)

### Coordinate Format (COO)

- In this format, the content is stored as a list of triplets ((row, column), element).
- This format is easiest to construct, especially for a very large matrix. We just have to know the shape of the matrix.
- Once the COO matrix is constructed, it is usually converted to CSR, CSC, or BSR for efficient computation.

- We can construct a COO matrix with the command `sp.coo_matrix` as follows. Note that all elements in repeated coordinates are accumulated.

In [ ]:
rows = rnd.randint(0, 10, size=8)
cols = rnd.randint(0, 5, size=8)
data = rnd.randn(8)
print(f'Rows = {rows}')
print(f'Cols = {cols}')
print(f'Data = {data}\n')

coo_a = sp.coo_matrix((data, (rows, cols)), shape=(10, 5))
print(f'COO Matrix A:\n{coo_a}\n')

mat_a = coo_a.toarray()                 # Convert to a dense matrix
print(f'Dense Matrix A:\n{mat_a}')

Rows = [5 6 0 2 3 5 4 2]
Cols = [2 3 2 4 4 0 1 0]
Data = [-0.92422659  0.70416762  1.08578006 -1.54838757 -0.70572901  0.10087198
 -0.57848312  0.03407658]

COO Matrix A:
  (5, 2)	-0.924226590663512
  (6, 3)	0.7041676197992061
  (0, 2)	1.0857800604377892
  (2, 4)	-1.5483875673522973
  (3, 4)	-0.7057290057573244
  (5, 0)	0.10087197536328409
  (4, 1)	-0.5784831192443961
  (2, 0)	0.03407657574923903

Dense Matrix A:
[[ 0.          0.          1.08578006  0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.03407658  0.          0.          0.         -1.54838757]
 [ 0.          0.          0.          0.         -0.70572901]
 [ 0.         -0.57848312  0.          0.          0.        ]
 [ 0.10087198  0.         -0.92422659  0.          0.        ]
 [ 0.          0.          0.          0.70416762  0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0

### Sparse Formats (CSR, CSC, and BSR)

- Once we have constructed the COO matrix, we then convert it to either the CSR, CSC, or BSR format for faster computation, such as arithmetic operations, slicing, and decomposition.

  - CSR matrix is suitable for row slicing and large matrix multiplication.

  - CSC matrix is suitable for column slicing and large matrix multiplication.

  - BSR matrix is suitable for dense sub-matrices.

- The CSR and CSC formats are more space-efficient than the BSR format, but the latter is more speed-efficient in arithmetic operations.
- In most cases, CSR and CSC are adequate for large matrix multiplication, while BSR is suitable for any computation related to dense sub-matrices such as finite element discretization.

In [ ]:
csr_a = coo_a.tocsr()
print(f'CSR Matrix A:\n{csr_a}')

CSR Matrix A:
  (0, 2)	1.0857800604377892
  (2, 0)	0.03407657574923903
  (2, 4)	-1.5483875673522973
  (3, 4)	-0.7057290057573244
  (4, 1)	-0.5784831192443961
  (5, 0)	0.10087197536328409
  (5, 2)	-0.924226590663512
  (6, 3)	0.7041676197992061


In [ ]:
csc_a = coo_a.tocsc()
print(f'CSC Matrix A:\n{csc_a}')

CSC Matrix A:
  (2, 0)	0.03407657574923903
  (5, 0)	0.10087197536328409
  (4, 1)	-0.5784831192443961
  (0, 2)	1.0857800604377892
  (5, 2)	-0.924226590663512
  (6, 3)	0.7041676197992061
  (2, 4)	-1.5483875673522973
  (3, 4)	-0.7057290057573244


In [ ]:
bsr_a = coo_a.tobsr()
print(f'BSR Matrix A:\n{bsr_a}')

BSR Matrix A:
  (0, 2)	1.0857800604377892
  (2, 0)	0.03407657574923903
  (2, 4)	-1.5483875673522973
  (3, 4)	-0.7057290057573244
  (4, 1)	-0.5784831192443961
  (5, 0)	0.10087197536328409
  (5, 2)	-0.924226590663512
  (6, 3)	0.7041676197992061


Of course, arithmetic operations can be applied to these formats.

In [ ]:
bsr_mult = bsr_a.T @ bsr_a

print(f'transpose(A) x A =\n{bsr_mult}\n')

print(f'Dense =\n{bsr_mult.toarray()}')

transpose(A) x A =
  (0, 2)	-0.09322856188350183
  (0, 4)	-0.05276374622806051
  (0, 0)	0.011336368428484617
  (1, 1)	0.3346427192507262
  (2, 0)	-0.09322856188350183
  (2, 2)	2.033113130533788
  (3, 3)	0.49585203677367923
  (4, 4)	2.8955574882983868
  (4, 0)	-0.05276374622806051

Dense =
[[ 0.01133637  0.         -0.09322856  0.         -0.05276375]
 [ 0.          0.33464272  0.          0.          0.        ]
 [-0.09322856  0.          2.03311313  0.          0.        ]
 [ 0.          0.          0.          0.49585204  0.        ]
 [-0.05276375  0.          0.          0.          2.89555749]]


-----
## Exercises 8

In Question 4.3, we have implemented the Power Method that computes the dominant eigenvector of any square matrix. The disadvantages of this algorithm are that it converges slowly and the convergence is rather unstable when the input matrix becomes very large and sparse (containing many zeros). In this exercise, we will implement an improvement version of the Power Method called **PageRank** (Brin and Page, 1998).

PageRank offers a more stable way to compute the dominant eigenvector of a very large matrix. The *damping factor* $\delta$ is introduced to the Power Method to stabilize the convergence. When the input matrix $\mathbf{M}$ is multiplied by the vector $\mathbf{v}^{(k)}$, we weight the resultant vector with $\delta$, smooth it with a constant $1 - \delta$, and normalize the result. Doing so will stabilize the convergence because of the smoothing process.

An overview of the algorithm is as follows. For a given square matrix $\mathbf{M}$:

  1. Let $\mathbf{v}^{(0)}$ be an arbitrary unit vector.
  2. For each $k$-th iteration
    1. We multiply $\mathbf{M}$ by an unit vector $\mathbf{v}^{(k)}$ to obtain a new vector $\mathbf{v}'$.
    2. We set $\mathbf{v}^{(k + 1)} = \delta \mathbf{v}' + (1-\delta) \mathbf{1}$, where $\mathbf{1}$ is a one vector. This step is called **smoothing**.
    3. Normalize $\mathbf{v}^{(k + 1)}$.
  3. We repeat the loop in Step 2 until $\mathbf{v}^{(k + 1)}$ becomes convergent.
  4. The resulted vector becomes the dominant eigenvector of $\mathbf{M}$.

In this exercise, we will implement PageRank using sparse matrices, simple matrix operations, and aggregation functions. We will also evaluate the speed of this implementation with a large sparse matrix.

### Question 8.1

Implement a function that normalizes an input vector. It should return a unit vector as a result.
$$
\begin{eqnarray}
    \mathrm{normalize}(\mathbf{v}) & = & \frac{\mathbf{v}}{\left\| \mathbf{v} \right\|}
\end{eqnarray}
$$

In [ ]:
# def normalize(vec):
#     return ___________          # Fill in this blank.

#### Solution

In [ ]:
def normalize(vec):
    return vec / la.norm(vec)

### Question 8.2

Implement a function that checks whether two <u>unit</u> vectors converge or not. In this exercise, vectors $\mathbf{v}_1$ and $\mathbf{v}_2$ are said to converge to each other if their Euclidean distance is less than the given threshold.
$$
\begin{eqnarray}
    \mathrm{dist}(\mathbf{v}_1, \mathbf{v}_2) & = & \left\| \mathbf{v}_1 - \mathbf{v}_2 \right\|\
\end{eqnarray}
$$
This function should return a boolean value indicating if $\mathbf{v}_1$ and $\mathbf{v}_2$ converge to each other or not.

In [ ]:
# def is_converge(vec1, vec2, threshold):
#     
#     # Compute the Euclidean distance between vec1 and vec2.
#     dist = __________
#     
#     # Return the boolean value that indicates the convergence with respect to the given threshold.
#     return __________

#### Solution

In [ ]:
def is_converge(vec1, vec2, threshold):
    
    # Compute the Euclidean distance between vec1 and vec2.
    dist = la.norm(vec1 - vec2)
    
    # Return the boolean value that indicates the convergence with respect to the given threshold.
    return dist <= threshold

### Question 8.3

Implement a function that computes the dominant eigenvector of a given square matrix $\mathbf{M}$. Read the instruction in the comments carefully and follow it accordingly.

In [ ]:
# def pagerank(matrix, threshold, maxiters, dampfact):
#     
#     # Find the first dimension of the given matrix.
#     dim = __________
#     
#     # Randomize an arbitrary unit vector using rnd.randn.
#     # Don't forget to normalize it before use.
#     vec = __________
#     
#     # Iterative Power Method
#     for i in range(maxiters):
#         
#         # Multiply the given matrix with the vector. Do not normalize it just yet.
#         matrix_vec = __________
#         
#         # Smooth the multiplication result with the damping factor. Also normalize the result of smoothing.
#         newvec = __________
#         
#         # If the obtained vector and the old vector converge, stop the iteration.
#         if is_converge(vec, newvec, threshold):
#             break
#             
#         # Otherwise, keep the obtained vector and continue the iteration.
#         else:
#             vec = newvec
#             
#     return newvec

#### Solution

In [ ]:
def pagerank(matrix, threshold, maxiters, dampfact):
    
    # Find the first dimension of the given matrix.
    dim = matrix.shape[0]
    
    # Randomize an arbitrary unit vector using rnd.randn.
    # Don't forget to normalize it before use.
    vec = rnd.randn(dim)
    
    # Iterative Power Method
    for i in range(maxiters):
        
        # Multiply the given matrix with the vector. Do not normalize it just yet.
        matrix_vec = matrix @ vec
        
        # Smooth the multiplication result with the damping factor. Also normalize the result of smoothing.
        newvec = normalize(dampfact * matrix_vec + (1 - dampfact))
        
        # If the obtained vector and the old vector converge, stop the iteration.
        if is_converge(vec, newvec, threshold):
            break
            
        # Otherwise, keep the obtained vector and continue the iteration.
        else:
            vec = newvec
            
    return newvec

### Question 8.4

Implement a function that computes an eigenvalue $\lambda$ of an eigenvector $\mathbf{v}$ with respect to an input matrix $\mathbf{M}$. The eigenvalue can be computed with the Rayleigh quotient below.
$$
\begin{eqnarray}
    \lambda & = & \frac{\mathbf{v}^\top \mathbf{M} \mathbf{v}}{\mathbf{v}^\top \mathbf{v}}
\end{eqnarray}
$$

In [ ]:
# def rayleigh(matrix, vec):
#     return __________

#### Solution

In [ ]:
def rayleigh(matrix, vec):
    return (vec.T @ matrix @ vec) / (vec.T @ vec)

### Question 8.5

Now let's implement a function that generate a large sparse matrix according to the given numbers of nodes and edges.

For example, we can create a matrix of size 7 whose total number of edges is 5 by calling `make_matrix(7, 5)`.

```python
>>> m = make_matrix(7, 5)
>>> print(m.toarray())
[[0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]
```

In [ ]:
# def make_matrix(no_nodes, no_edges):
#     
#     # Randomize a sequence of row IDs, whose length is equal to no_edges.
#     # Each row ID is in the range [0, no_nodes).
#     rows = __________
#     
#     # Randomize a sequence of column IDs, whose length is equal to no_edges.
#     # Each column ID is in the range [0, no_nodes).
#     cols = __________
#     
#     # This is the frequency count for each edge.
#     data = np.ones(no_edges)
#     
#     # Create a COO sparse matrix out of rows, cols, and data.
#     coo_m = __________
#     
#     # Convert coo_m to a CSR sparse matrix.
#     csr_m = __________
#     
#     return csr_m

#### Solution

In [ ]:
def make_matrix(no_nodes, no_edges):
    
    # Randomize a sequence of row IDs, whose length is equal to no_edges.
    # Each row ID is in the range [0, no_nodes).
    rows = rnd.randint(0, no_nodes, no_edges)
    
    # Randomize a sequence of column IDs, whose length is equal to no_edges.
    # Each column ID is in the range [0, no_nodes).
    cols = rnd.randint(0, no_nodes, no_edges)
    
    # This is the frequency count for each edge.
    data = np.ones(no_edges)
    
    # Create a COO sparse matrix out of rows, cols, and data.
    coo_m = sp.coo_matrix((data, (rows, cols)), shape=(no_nodes, no_nodes))
    
    # Convert coo_m to a CSR sparse matrix.
    csr_m = coo_m.tocsr()
    
    return csr_m

### Question 8.6

**Testing:** You can test your implementation with the following simple code.

In [ ]:
# m = make_matrix(1000, 20000)
# 
# v = pagerank(m, 1e-3, 20, 0.85)
# print(v)

#### Solution

In [ ]:
m = make_matrix(1000, 20000)

v = pagerank(m, 1e-3, 20, 0.85)
print(v)

[0.03677863 0.02792465 0.02590043 0.02965874 0.03578196 0.0294951
 0.02694176 0.03311035 0.02857742 0.0340131  0.02708807 0.02549885
 0.02506034 0.03392155 0.029174   0.04007985 0.02996154 0.03011105
 0.03101822 0.02922578 0.02995185 0.02831653 0.02896782 0.03436052
 0.04315214 0.04412104 0.02540152 0.02310839 0.0296743  0.0392473
 0.03162087 0.02862643 0.03106618 0.03552686 0.03305606 0.02906403
 0.02203608 0.03559419 0.02592635 0.02728904 0.03924241 0.04199795
 0.03734114 0.03574796 0.04601969 0.03410772 0.02679374 0.03113493
 0.04193116 0.02937169 0.03393524 0.03416797 0.02786408 0.02520943
 0.03140618 0.0320148  0.03919458 0.02569003 0.02783204 0.0308671
 0.03216643 0.02508208 0.03870879 0.03466359 0.03612623 0.02967359
 0.03157502 0.03013691 0.03946206 0.0301426  0.03277121 0.0374171
 0.02481978 0.03171123 0.02216923 0.03634123 0.03158406 0.02993617
 0.02530806 0.03385271 0.03275598 0.03725945 0.02001635 0.03293922
 0.03057223 0.03121157 0.02031703 0.0294462  0.03067474 0.01930992

-----